### ISSUE TITLE
Whitelisted units used to only have to hit 3 times to build/destroy objs

### ISSUE THREAD

**Issue by wescottj98** [Bro-Nation/Mike-Force#14]
**Is your feature request related to a problem? Please describe.**
Whitelisted units used to only have to hit 3 times to build/destroy objs, now they must do it up to 5 times. elephant grass used to take 1 hit, now takes 3.

Source: CDR Louis "Old Man" Rust

**Describe the solution you'd like**
n/a

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by cerebral-314** [comment]
Fairly certain you fixed this already.
