### ISSUE TITLE
Mike Force sometimes do not get the option to capture DC

### ISSUE THREAD

**Issue by wescottj98** [Bro-Nation/Mike-Force#20]
**Describe the bug**
Mike Force sometimes do not get the option to capture DC. Still get the option to stabilize drag and carry though.

**To Reproduce**
Steps to reproduce the bug (If you can't reproduce it, just give details of what happened beforehand. Anything you think could be relevant):

**Expected behaviour**
Capture should pop up when dc are downed

**Screenshots**

**Environment (please complete the following information):**
Version: 
Map (specify if Altis Blufor): 

* [x] Official Server
* [ ] Official InDev Server
* [ ] Private dedicated server
* [ ] Private dedicated server with Headless client(s)
* [ ] LAN Hosted

Additional mods:
    
Time the bug occurred (Please leave in GMT+0):
If **Not** on an official server, please leave the time zone of your client for LAN, or the server for dedicated: 

**Additional context**

If you were LAN hosting, please attach your client .RPT file from when the bug occurred, If on a private dedicated server, please attach the server's .RPT from when the bug occurred.

**Comment by cerebral-314** [comment]
Fixed a while back
