### ISSUE TITLE
DC helicopters at dc NW base are not locked and cannot be used

### ISSUE THREAD

**Issue by wescottj98** [Bro-Nation/Mike-Force#22]
**Describe the bug**
DC helicopters at dc NW base are not locked and cannot be used
**To Reproduce**
Steps to reproduce the bug (If you can't reproduce it, just give details of what happened beforehand. Anything you think could be relevant): Tried to get in helicopter and could not, blew up helicopter and it did not respawn

**Expected behaviour**
should present an unlock button which should then allow access

**Screenshots**

**Environment (please complete the following information):**
Version: 
Map (specify if Altis Blufor): 

* [x] Official Server
* [ ] Official InDev Server
* [ ] Private dedicated server
* [ ] Private dedicated server with Headless client(s)
* [ ] LAN Hosted

Additional mods:
    
Time the bug occurred (Please leave in GMT+0):
If **Not** on an official server, please leave the time zone of your client for LAN, or the server for dedicated: 

**Additional context**

If you were LAN hosting, please attach your client .RPT file from when the bug occurred, If on a private dedicated server, please attach the server's .RPT from when the bug occurred.

**Comment by cerebral-314** [comment]
All DC choppers should respawn properly and work now sorry for that.
