### ISSUE TITLE
Enemy vehicle whitelist

### ISSUE THREAD

**Issue by Roughneck1-2** [Bro-Nation/Mike-Force#33]
**Is your feature request related to a problem? Please describe.**

The problem im starting to get really frustrated about is the enemy vehicles not being whitelisted i know an attempt to add whitelist to enemy aircraft was made in aos but it seems that is no longer working as it should and people are back to abusing these vehicles to bypass whitelisted stuff like enemy howitzers to use their own versions of the 105s enemy cas aircraft be it helicopters or fixed wing to bypass muskets and satans angels restrictions and then the tanks in the ao which are constantly firing at or nearby friendlies.

**Describe the solution you'd like**

Honestly all i want is for all vc vehicles to be put under a whitelist for dac cong so no blufor can get in them as it will prevent a ton of friendly fire from happening and units rules being negated note people are using the glitch of swapping seats in vehicles to access the slots they can drive/pilot them in

**Describe alternatives you've considered**

My only alternative i have considered that i know is not gonna happen is remove them from spawning all together but thats not fair on dac cong players 

**Additional context**

Had two incidents today where people got upset cause they got killed while in a enemy vehicle even though they knew they werent supposed to ve ontop of striking near friendlies  i dont got any screenshots to go with it yet from today.

**Comment by cerebral-314** [comment]
I think I got a fix... will be rolled out soon.
