### ISSUE TITLE
Multiple AOs being triggered at once, possibly blocking 1st AO from completing.

### ISSUE THREAD

**Issue by dijksterhuis** [Bro-Nation/Mike-Force#34]
**Describe the bug**
A couple of instances of 2x AOs being triggered into the Red Stage i.e. spawning spike team objectives. I was under the impression that recent changes should mean current AO is locked to only the one that was previously blue preparation stage (at least that is the impression I got after the relevant round table meeting).

See relevant discord message links for players reporting the issue:
- https://discord.com/channels/494435095168548866/504240588816908290/1016881935009726566
- https://discord.com/channels/494435095168548866/557923267713957899/1016361774557171773

Second discord link indicates that completing all the Spike team objectives in the 2nd AO may cause the 1st AO to switch over to "Yellow". If so, not a critical issue so long as there is someone on server who knows about this "gotcha".

**To Reproduce**
Unknown. Possibly players heading into a 2nd AO. Or some server issues (a subsequent [discord post](https://discord.com/channels/494435095168548866/504240588816908290/1016888114813354064) mentioned server missed it's last scheduled restart time).

**Expected behaviour**
Only 1x AO should be able to be triggered at a time (the AO that was previously marked for preparation).

**Screenshots**
![image](https://user-images.githubusercontent.com/11841332/188769539-0ce4befd-2510-440a-b871-76d2e9e55f91.png)

**Environment (please complete the following information):**
Version: 1.00.01 + BN
Map (specify if Altis Blufor): CamLaoNam
BN Server: BN Mike Force #1

Additional mods:
n/a
    
Time the bug occurred (Please leave in GMT+0):
See linked discord message timestamps.

**Additional context**

**Comment by dijksterhuis** [comment]
Edited title as unsure if it is due to either players or server being "difficult".

**Comment by cerebral-314** [comment]
Server definitely was being difficult, but I'll add additional checks. Pretty sure the auto-restarter wasn't on last night which resulted in the mission running far too long.
