### ISSUE TITLE
Cargo ropes

### ISSUE THREAD

**Issue by Roughneck1-2** [Bro-Nation/Mike-Force#35]
**Describe the bug**

I noticed all of yesterday that any time someone tried to sling load a bulldog it would lag for a couple seconds upon take off and the ropes would just snap tossing the tank like a slingshot

**To Reproduce**
Steps to reproduce the bug (If you can't reproduce it, just give details of what happened beforehand. Anything you think could be relevant):

The way to reproduce this is grab one of the black hawk whitelisted bulldogs and single cargo sling load it to a green hornets slick (havent tested it on the other helicopters yet) have the helicopter take of and give it a few seconds of moving before the ropes just detach.

**Expected behaviour**

What was supposed to happen is well you know it gets lifted to destination

**Screenshots**

I do not have screenshots of it i will be hoping on soon here to try and get some as it was late at night when i noticed this

**Environment (please complete the following information):**
Version: current up to date version of mikeforce
Map (specify if Altis Blufor): bronations server 1

* [ ] Official Server
* [ ] Official InDev Server
* [ ] Private dedicated server
* [ ] Private dedicated server with Headless client(s)
* [ ] LAN Hosted

Additional mods:base mods allowed in bro nations server 1 (lambs,enhanced movement,cba cant remember the last ones name off the top of my head)
    
Time the bug occurred (Please leave in GMT+0):roughly between 6am-9am GMT+0
If **Not** on an official server, please leave the time zone of your client for LAN, or the server for dedicated: 

**Additional context**

This is rather new to me im thinking it may have happened from the latest arma 3 update patch 

If you were LAN hosting, please attach your client .RPT file from when the bug occurred, If on a private dedicated server, please attach the server's .RPT from when the bug occurred.

**Comment by cerebral-314** [comment]
Modified the bandwidth settings to be alittle more lax... should solve this
