### ISSUE TITLE
New map issues

### ISSUE THREAD

**Issue by Roughneck1-2** [Bro-Nation/Mike-Force#36]
**Describe the bug**

Nothing shows up on map when downed and everything player wise when alive flickers in and out only person i could consistently see was people in zeus position

**To Reproduce**
Steps to reproduce the bug (If you can't reproduce it, just give details of what happened beforehand. Anything you think could be relevant):

Uh get shot and revive that's about only way i know to reproduce

**Expected behaviour**

Honestly i have no idea it all started happening after the 26mb patch and got worse after the most recent 28gb update

**Screenshots**

**Environment (please complete the following information):**
Version: 
Map (specify if Altis Blufor): 
MikeForce Server 1 (havent tried any other servers yet)
* [ ] Official Server
* [ ] Official InDev Server
* [ ] Private dedicated server
* [ ] Private dedicated server with Headless client(s)
* [ ] LAN Hosted

Additional mods:

All bro nation approved mods for server 1
    
Time the bug occurred (Please leave in GMT+0): 4am GMT+0
If **Not** on an official server, please leave the time zone of your client for LAN, or the server for dedicated: 

**Additional context**

Seems to ve consistent when going down but the part when alive is constant flickering

If you were LAN hosting, please attach your client .RPT file from when the bug occurred, If on a private dedicated server, please attach the server's .RPT from when the bug occurred.

**Comment by cerebral-314** [comment]
Fixed
