### ISSUE TITLE
The Bra -- Capture mechanic sends player to their own side's cage locations

### ISSUE THREAD

**Issue by dijksterhuis** [Bro-Nation/Mike-Force#41]
**Describe the bug**
- BLUEFOR capture sends OPFOR player to OPFOR cages
- OPFOR capture sends BLUEFOR player to BLUEFOR cages

**Frequency**
How often does this bug happen? (place an 'x' between the square brackets below)

* [ ] At most once a week 
* [ ] At most once per day
* [ ] Every restart cycle
* [ ] Every AO
* [x] Constant and persistent

**Impact**

DC can still RP in the field before capture and seems to work okay as a "nope, go back to base and start again" mechanic for now.

No chance of RPing at the DC cages though.

* [ ] Almost none
* [x] Minor annoyances
* [ ] Interrupts gameplay
* [ ] I've died to it a few times
* [ ] Game is unplayable

**Scope**

* [ ] Only me
* [ ] A handful of unrelated players
* [ ] A specific unit (example: SASR)
* [ ] A specific team (example: all Spike teams)
* [ ] A specific side (example: all of BLUEFOR)
* [x] All players
* [ ] Zeuses

**Temporary workarounds**
As before, DC/MF can RP in field for now.

**Reproduction**
Get captured!

**Expected behaviour**
- BLUEFOR capture mechanic should TP OPFOR player to BLUEFOR cages
- OPFOR capture mechanic should TP BLUEFOR player to OPFOR cages

**Screenshots / Videos**
Will do later.

**Discord posts**
Will post in help and link back here.

**Your Bro Nation In-Game Name**
- 05  SGT. DJ Dijksterhuis

**Your Bro Nation Discord Name**
- 05 SGT. DJ Dijksterhuis
- dijksterhuis#3742

**Bro-Nation Server**
Which server did the bug happen on:
* [x] BN MF 1 (https://www.battlemetrics.com/rcon/servers/14443958)
* [ ] BN MF 2 (https://www.battlemetrics.com/rcon/servers/13401008)
* [ ] BN MF 3 (No Whitelist) (https://www.battlemetrics.com/rcon/servers/4478492)
* [ ] BN MF 5 (Unsung) (https://www.battlemetrics.com/rcon/servers/15066721)
* [ ] BN MF Training 1 (https://www.battlemetrics.com/rcon/servers/14997108)
* [ ] Local Development Environment

**Bro-Nation Server**
Which map was loaded when the bug happened:
* [ ] CamLaoNam
* [ ] KheSahn
* [x] Bra
* [ ] Altis

**Mods**:
n/a

**Approx. Time of Bug**:
Occurring over the last two days.

**Additional context**

Silverhand + Magician 1-1 were captured by myself while they were BLUEFOR and were the ones who reported they were sent to BLUEFOR cages.

Rage was captured by BLUEFOR and DC could see him on map 200-300m south west of DC HQ.

**Comment by cerebral-314** [comment]
fixed
