### ISSUE TITLE
Move Quarterhorse 105s to FSB Berchesgarden

### ISSUE THREAD

**Issue by wescottj98** [Bro-Nation/Mike-Force#54]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by dijksterhuis** [comment]
This can be closed, right? Paid a visit to the new FSB and looked good.

**Comment by wescottj98** [comment]
Yes I documented it here but forgot to update and close it

**Comment by dijksterhuis** [comment]
o7
