### ISSUE TITLE
Players lose ground and air channel after they die and respawn.

### ISSUE THREAD

**Issue by sjindra31** [Bro-Nation/Mike-Force#86]
**Describe the bug**
Players lose ground and air channel after they die and respawn. They then have to open H menu and rejoin it.
**Frequency**
How often does this bug happen? (place an 'x' between the square brackets below)
After every death
* [ ] At most once a week 
* [ ] At most once per day
* [ ] Every restart cycle
* [ ] Every AO
* [X] Constant and persistent

**Impact**
How much of an impact does this bug have on gameplay? (place an 'x' between the square brackets below)
Players will forget to rejoin or simply do not know how to rejoin. Makes communication with new players hard.
* [ ] Almost none
* [ ] Minor annoyances
* [X] Interrupts gameplay
* [ ] I've died to it a few times
* [ ] Game is unplayable

**Scope**
How many players (estimated) does this bug affect? (place an 'x' between the square brackets below)
Everyone is affected.
* [ ] Only me
* [ ] A handful of unrelated players
* [ ] A specific unit (example: SASR)
* [ ] A specific team (example: all Spike teams)
* [X] A specific side (example: all of BLUEFOR)
* [ ] All players
* [ ] Zeuses

If applicable, please list the specific units / teams affected:

**Temporary workarounds**
Are there any known workarounds / temporary fixes for the problem?
None, just have to open H menu and rejoin.
**Reproduction**
If applicable, can this bug be made to happen on-demand? Are there any specific steps/actions the development team need to perform to make the bug happen for them? Anything you think could be relevant. Please be detailed here!
Any time after death, even if manually respawning.
**Expected behaviour**
A clear and concise description of what you expected should happen (instead of what actually happened).
We should stay on the ground/air channel after respawning.
**Screenshots / Videos**
If applicable, attach suitable screenshots/videos of the bug to help explain your problem. 

For SCREENSHOTS: Place the text cursor in the empty space below this line and follow the instructions at the bottom of the editor window.

For VIDEOS: upload to a hosting service like YouTube first and paste the link here.

**Discord posts**
If applicable, add links to discord posts of players reporting the problem.

**Your Bro Nation In-Game Name**
If applicable, what is your in-game name for Bro Nation servers (to help searching through the Arma3 log files).

**Your Bro Nation Discord Name**
If applicable, what is your discord name for Bro Nation servers (to help in communicating with players about the bug).
Leumas#0181
**Bro-Nation Server**
Which server did the bug happen on:
* [X] BN MF 1 (https://www.battlemetrics.com/rcon/servers/14443958)
* [ ] BN MF 2 (https://www.battlemetrics.com/rcon/servers/13401008)
* [ ] BN MF 3 (No Whitelist) (https://www.battlemetrics.com/rcon/servers/4478492)
* [ ] BN MF 5 (Unsung) (https://www.battlemetrics.com/rcon/servers/15066721)
* [ ] BN MF Training 1 (https://www.battlemetrics.com/rcon/servers/14997108)
* [ ] Local Development Environment

**Bro-Nation Server**
Which map was loaded when the bug happened:
* [X] CamLaoNam
* [ ] KheSahn
* [ ] Bra
* [ ] Altis

**Mods**:
Which, if any, mods were loaded when you experienced the bug? If the bug is something like a map specific issue or arsenal whitelisting feel free to ignore this.

**Approx. Time of Bug**:
Time the bug occurred. Please indicate your TIMEZONE or convert it to UTC / GMT timezone!
Been going on for months, unsure if it was ever documented 
**Additional context**

**Comment by dijksterhuis** [comment]
o7
