### ISSUE TITLE
Eating oranges make you sick

### ISSUE THREAD

**Issue by wescottj98** [Bro-Nation/Mike-Force#9]
**Describe the bug**
 eating more than 3 oranges gives you diarrheas

Source: CDR Louis "Old Man" Rust

**To Reproduce**
Steps to reproduce the bug (If you can't reproduce it, just give details of what happened beforehand. Anything you think could be relevant): ate 3 oranges

**Expected behaviour**
expect not to get sick

**Screenshots**
n/a

**Environment (please complete the following information):**
Version: 
Map (specify if Altis Blufor): 

* [x] Official Server - I assume it happened here
* [ ] Official InDev Server
* [ ] Private dedicated server
* [ ] Private dedicated server with Headless client(s)
* [ ] LAN Hosted

Additional mods:
    
Time the bug occurred (Please leave in GMT+0):
If **Not** on an official server, please leave the time zone of your client for LAN, or the server for dedicated: 

**Additional context**

If you were LAN hosting, please attach your client .RPT file from when the bug occurred, If on a private dedicated server, please attach the server's .RPT from when the bug occurred.

**Comment by cerebral-314** [comment]
As it should... this was intended.
